# Site settings
author: Matthew Serre
title: From First Step to Flatiron
header-img: img/home-bg.png
email: matthew.serre@gmail.com
copyright_name: Matthew Serre
description: > # this means to ignore newlines until "baseurl:"
  A journey into the world of web development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MatthewSerre

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
